name: Java Maven Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set timezone to Asia/Kathmandu and show time
        run: |
          export TZ=Asia/Kathmandu
          date

      - name: Build and run tests (ignore failures)
        env:
          TZ: Asia/Kathmandu
        run: mvn -B package -Dmaven.test.failure.ignore=true

      - name: Archive Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
